version: '3.9'
services:
  home:
    build: .
    dns:
     - 8.8.8.8
     - 8.8.4.4
    container_name: main_ariakish
    ports:
      - "3003:3000"
    env_file:
      - .env
    volumes:
      #- .:/app
      - /app/node_modules
    command: npm start
